### ISSUE TITLE
Export images from 3D viewer

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiAuto#10]
From https://github.com/INTI-CMNB/KiBot/issues/99#issuecomment-968129830

I made a sample script to generate captures from the 3D Viewer.  
It's a start to integrate image generation from the 3D viewer by extending KiAuto/src/pcbnew_do .

The basic export would already be great while allowing configuration of:
- Virtual/SMD/THT component selection (by simulating V,S and T keys);
- How much to zoom the view (expressed in number of 'mouse roller click 4' to be simulated);
- Back, front export.

Of course there are more options, and one could imagine even doing a video capture of the model being turned around to get a better feel about the 3D aspects of the design.

This was generated using the sample script:

![image](https://user-images.githubusercontent.com/1504752/141657695-c35cde82-d915-4dc6-bfd1-7654c8ca7c05.png)
![image](https://user-images.githubusercontent.com/1504752/141657696-a239d60d-2b3c-41f6-a372-2ea86c11e655.png)

Script to be run as `./gen3DCaptures t1` in the docker VM where t1 is the project name of the demo project: 
[gen3DCaptures.zip](https://github.com/INTI-CMNB/KiBot/files/7532676/gen3DCaptures.zip)

**Comment by set-soft** [comment]
Hi @mdeweerd !

Thanks for the script. I implemented it on KiAuto. So now:

```
pcbnew_do 3d_view --zoom=5 --output_name=top.png  --ray_tracing t1.kicad_pcb .
```

Generates:

![top](https://user-images.githubusercontent.com/22823627/142260554-6a22a45b-3ae5-470f-9242-d6a7589579b9.png)

And:
```
pcbnew_do 3d_view --zoom=5 --output_name=bottom.png --view=Z --ray_tracing t1.kicad_pcb .
```

Generates:

![bottom](https://user-images.githubusercontent.com/22823627/142260675-4b576cb2-50b9-4fd6-84a9-1c944924abef.png)

For some reason the regular (no ray tracing) outputs are quite raw:

![top_no_rt](https://user-images.githubusercontent.com/22823627/142261133-c3d43b11-64b1-4714-b643-abf9d29822f1.png)

Not sure if I'm missing some KiCad option or is related to the X virtual server.

**Comment by mdeweerd** [comment]
That's great ;-).  I think you'll get this in KiBot soon ;-).

I generated my 3D Images using setsoft/kicad_auto:latest or setsoft/kicad_auto:dev running on Windows with VcXsrvr .  
As the images are generated/exported the the 3DViewer, I'ld be surprised that it depends on the XServer, but why not.
I think raytracing was on, but I did not set it (I think the reset should have).

Anyway, this is a great addition as the 3D model library is more complete than the 2D model library.  If KiCAD would have an orthogal option, then we'd have a true 2D top view as well.

With the variant filtering we'll get a good realisitic view of what the board looks like.

**Comment by set-soft** [comment]
> That's great ;-). I think you'll get this in KiBot soon ;-).

Committed a poorly tested implementation a few seconds ago ;-)

**Comment by set-soft** [comment]
> If KiCAD would have an orthogal option, then we'd have a true 2D top view as well.

Take a look at the last patch, works using a very delicated mechanism, but you get:

![t1-3D_top](https://user-images.githubusercontent.com/22823627/142284410-ef226b94-421e-44d2-8cbc-e893bec805bf.png)
![t1-3D_bottom](https://user-images.githubusercontent.com/22823627/142284425-22c3e01c-21c6-4ae2-b5ba-c14fb5462a69.png)

**Comment by mdeweerd** [comment]
I had a look at the patch - KiCADs way ?! - I do not even see it on screen.  Not WYSIWYG but something like YGWYDS ?  (You get what you do not see?).
But hey, it seems to be there since 2017.  I never noticed the cube...
I didn't search for it because I thought it did not exist yet.

That's great - the previous 2D implementation is clearly outperformed!  Hard to do better than that!

I'll see iv the selection of these icons can't be improved.

**Comment by mdeweerd** [comment]
Well, there's no way to select the toolbar from the keyboard - none of my tricks worked :-(.

Anyway, it works, one more reason to use KiAuto (and KiBot - I am going to test that).
