### ISSUE TITLE
pcbnew_do not working with kicad 6.0.2

### ISSUE THREAD

**Issue by flaminggoat** [INTI-CMNB/KiAuto#15]
The script does not seem to interact with the window, I have tried exporting the 3d_view with recording enabled. The pcbnew window opens and then no further interaction happens. Strangely when running with vnc enabled, the script progresses further,and actually opens the 3d view window. 

```
theo@T440s:~/source/KiAuto/src$ ./pcbnew_do -rv 3d_view ../tests/kicad6/good-project/good-project.kicad_pcb .
INFO:Waiting for "Main pcbnew window" ...
INFO:Open 3D viewer
INFO:Waiting for "3D Viewer" ...
Traceback (most recent call last):
  File "./pcbnew_do", line 1016, in <module>
    capture_3d_view(cfg)
  File "./pcbnew_do", line 459, in capture_3d_view
    wait_for_window('3D Viewer', '3D Viewer')[0]
  File "/home/theo/source/KiAuto/kiauto/ui_automation.py", line 400, in wait_for_window
    raise RuntimeError('Timed out waiting for %s window' % name)
RuntimeError: Timed out waiting for 3D Viewer window

```

Before installing kicad 6.0.2 the script worked fine on my PC with kicad 5.

pcbnew_do 1.6.3
kicad 6.0.2-378541a8eb~116~ubuntu20.04.1, release build

**Comment by set-soft** [comment]
Hi @flaminggoat !
KiCad 6.0.0 was affected by a bug that prevented opening the 3D Viewer if no hardware OpenGL was available, this is always the case for the virtual X server.
Now this bug is fixed, so I was able to implement the functionality.
