### ISSUE TITLE
[BUG] ERC exclutions are still reported as errors

### ISSUE THREAD

**Issue by korken89** [INTI-CMNB/KiAuto#31]
**Describe the bug**
When having a schematic with an ERC error, that is marked as an exclusion, the ERC check still errors saying there is an ERC error.

**To Reproduce**
Make a schematic and connect 2 outputs to each other, run ERC and mark the error as exclusion, run kibot ERC.

**Expected behavior**
The exclusion should not generate an error.

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow? (Ex: `GitHub`/`GitLab`) No
- In a GitHub action? Which tag are you using? (Ex `v1`, `v1_k6`, `v2`, `v2_d`, `v2_dk6`, `v2_k6`) No
- Using a docker image? (Ex: `kicad_auto:ki6`, `kicad_auto:latest`, `kicad_auto:dev`, `kicad_auto:dev_k6`, a custom one? can you provide the `Dockerfile`) No
- Using a desktop system? Which OS, distro and version? Arch Linux (also tested on Gitlab CI with the same error)

**Comment by set-soft** [comment]
Hi @korken89 !
Thanks for reporting.
I transferred the issue to KiAuto because this is the tool that does the ERC stuff.
Now we detect the exclusions and they are subtracted from the total count, and the messages are discarded.

**Comment by korken89** [comment]
Thank you for fixing!
