### ISSUE TITLE
kicad2step_do ERROR:False

### ISSUE THREAD

**Issue by MadAnonMan** [INTI-CMNB/KiAuto#34]
I am in the process of updating our build server from [kicad7_auto:1.6.2](https://github.com/INTI-CMNB/kicad_auto/pkgs/container/kicad7_auto/97351029?tag=1.6.2) to [kicad7_auto:1.6.3](https://github.com/INTI-CMNB/kicad_auto/pkgs/container/kicad7_auto/139911060?tag=1.6.3) and there is a error that has popped up in relation to 3D Model generation. The error isn't stopping the build and a model is still generated.

![image](https://github.com/INTI-CMNB/KiAuto/assets/81274690/9dd3245f-6db2-4a6c-b6ec-9bcfe2b03535)

Looking at a verbose log file does not give any other hints to why the error has occured.

> INFO:KiCad to STEP wrapper
> ERROR:False (kicad2step_do - kicad2step_do:140)
> DEBUG:Command: ['kicad-cli', 'pcb', 'export', 'step', '-o', '/data/datapack/test/ASSY_test/Render3D/test-B-3D.step', '-f', '--grid-origin', '--no-virtual', '--min-distance=0.0001mm', '--subst-models', '/data/tmpbuswqqwj.kicad_pcb'] (kicad2step_do - kicad2step_do:150)
> INFO:Loading board
> Determining PCB data
> Board Thickness from stackup: 1.580 mm

 So I have done a little digging and it seems the error is produced when setting ` no_virtual: true`  in the options for `type: 'step'`. The error is getting printed on  [kicad2step_do.py:140](https://github.com/INTI-CMNB/KiAuto/blob/master/src/kicad2step_do#L140C1-L141C1) which was added in this [commit ](https://github.com/INTI-CMNB/KiAuto/commit/8a86547bd2b3b96d89947ded2844381be65670cc). 

Does this error actual have a purpose or is it just a left over debug print.

**Comment by set-soft** [comment]
Hi @MadAnonMan !
Thanks for reporting, it was a debug message to check if the script detected KiCad 8. Now removed on the git code.
