### ISSUE TITLE
Arch does not have locale C.UTF-8

### ISSUE THREAD

**Issue by paulsykes** [INTI-CMNB/KiAuto#9]
Local is specifically set to C.UTF-8. Arch Linux, and a number of other distros do not support this locale.

```
# Force english + UTF-8
os.environ['LANG'] = 'C.UTF-8'
```

This results in a un-handled warning dialogue, which causes a timeout.

![unhandled_warning](https://user-images.githubusercontent.com/3183979/140745737-1b5ea864-b0eb-4e15-87e7-1d6bf73f0988.png)

```
$ eeschema_do --record -v run_erc ft231x_uart_usb_power_switch.sch out/
INFO:Waiting for "Main eeschema window" ...
INFO:Waiting for "Main eeschema window" ...
ERROR:Time-out waiting for eeschema, giving up (eeschema_do - eeschema_do:157)
```
Changing from 'C.UTF-8' to 'en_US.UTF-8' appears to fix the issue. However, I have not exhaustively tested all functionality.

**Comment by set-soft** [comment]
Hi @paulsykes !
This is quite strange because:

1. The dialog says KiCad can't set "en_US", not "C".
2. "C" is just "default C language", not supporting it looks like a deeply broken locale setup. When I want to force a program to use its default language I run `LANG=C PROGRAM`, I used it for the last 25 years without problems, on Linux and even on DOS (DJGPP).

I can't change it to `en_US` because then it will break on any setup that really uses locales. It will work only for people in US, it could even fail for british people. Debian derived installations (and this includes Ubuntu) only installs the locales you want to install, so you can't assume people has `en_US` installed. But `C` isn't a human language, is just the default locale setting, which are the same as `en_US`.

Can you try using `C`, without the encoding?

**Comment by paulsykes** [comment]
@set-soft actually the outcome is slightly different. Same log output
```
 eeschema_do --record -v run_erc ft231x_uart_usb_power_switch.sch out/
INFO:Waiting for "Main eeschema window" ...
INFO:Waiting for "Main eeschema window" ...
ERROR:Time-out waiting for eeschema, giving up (eeschema_do - eeschema_do:157)
```
However replaying the recorded video, shows the same frame for 60 seconds. This time the warning message does not appear. It looks like it is waiting for something.
![Selection_002](https://user-images.githubusercontent.com/3183979/140769735-a994d59d-5efb-4265-9c08-df60befc0b3e.png)

**Comment by paulsykes** [comment]
@set-soft also my output of locale for reference
```
$ locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

**Comment by paulsykes** [comment]
@set-soft 

Looks like the xdotool search is failing when eeschema is started with LANG=C.

I wrote this small script
```
#!/bin/bash
while true
do
	xdotool getactivewindow getwindowname
	xdotool search --onlyvisible --name 'Eeschema.'
	sleep 1
done
```
eeschema is launched with no LANG argument, both window name and id appear as expected.
```
$
Eeschema — noname.sch
56623123
Eeschema — noname.sch
56623123
Eeschema — noname.sch
56623123
Eeschema — noname.sch
56623123
Eeschema — noname.sch
56623123
```
launching eeschema using $ LANG=C eeschema,  only the window name appears, no id, indicating the xdotool search fails.
```
$
Eeschema — noname.sch
Eeschema — noname.sch
Eeschema — noname.sch
Eeschema — noname.sch
Eeschema — noname.sch
```

**Comment by paulsykes** [comment]
@set-soft interesting comment here

https://hub.docker.com/r/productize/kicad-automation-scripts/dockerfile/
```
# Use a UTF-8 compatible LANG because KiCad 5 uses UTF-8 in the PCBNew title
# This causes a "failure in conversion from UTF8_STRING to ANSI_X3.4-1968" when
# attempting to look for the window name with xdotool.
ENV LANG C.UTF-8
```

**Comment by paulsykes** [comment]
@set-soft looks like C.UTF-8 not being supported in Arch seems to be a re-occuring 'feature' for other projects. 

https://github.com/rakudo/star/issues/161

Whilst this is not ideal, would you be open to falling back to en_US.UTF-8 if it is detected that C.UTF-8 is not supported?

**Comment by paulsykes** [comment]
@set-soft some useful context here.

https://unix.stackexchange.com/questions/597962/how-widespread-is-the-c-utf-8-locale

**Comment by set-soft** [comment]
> @set-soft interesting comment here
> 
> https://hub.docker.com/r/productize/kicad-automation-scripts/dockerfile/
> 
> ```
> # Use a UTF-8 compatible LANG because KiCad 5 uses UTF-8 in the PCBNew title
> # This causes a "failure in conversion from UTF8_STRING to ANSI_X3.4-1968" when
> # attempting to look for the window name with xdotool.
> ENV LANG C.UTF-8
> ```

Yes I remember about this, if we don't use UTF-8 the window titles with UTF-8 text can't be detected.

**Comment by set-soft** [comment]
@paulsykes please test it on your system.

Now the code runs `locale -a` and selects a locale matching `en*UTF8`. We only use `C.UTF-8` if `locale` isn't installed or when the system doesn't support english (and supports `C.UTF-8`).

If `locale` isn't available we issue a warning.

If english and `C.UTF-8` aren't supported we ask to configure the system.

**Comment by paulsykes** [comment]
@set-soft tested, looks good. Many thanks for fixing this.
